#!/usr/bin/env ruby
# frozen_string_literal: true

SOURCE_BIB = File.expand_path("../publications.bib", __dir__)
TARGET_MD = File.expand_path("../papers.markdown", __dir__)
SCHOLAR_URL = "https://scholar.google.com/citations?user=9R0fnL8AAAAJ"

Entry = Struct.new(:key, :fields)

def extract_entries(text)
  entries = []
  i = 0

  while i < text.length
    at = text.index("@", i)
    break unless at

    open = text.index("{", at)
    break unless open

    depth = 0
    j = open
    while j < text.length
      char = text[j]
      depth += 1 if char == "{"
      depth -= 1 if char == "}"
      if depth.zero?
        entries << text[at..j]
        i = j + 1
        break
      end
      j += 1
    end
    break if j >= text.length
  end

  entries
end

def parse_fields(body)
  fields = {}
  i = 0

  while i < body.length
    i += 1 while i < body.length && [" ", "\n", "\t", ","].include?(body[i])
    break if i >= body.length

    start = i
    i += 1 while i < body.length && body[i].match?(/[A-Za-z_]/)
    name = body[start...i]&.downcase
    break if name.nil? || name.empty?

    i += 1 while i < body.length && [" ", "\n", "\t"].include?(body[i])
    break unless body[i] == "="
    i += 1
    i += 1 while i < body.length && [" ", "\n", "\t"].include?(body[i])

    value = nil
    if body[i] == "{"
      depth = 0
      start_val = i + 1
      i += 1
      while i < body.length
        depth += 1 if body[i] == "{"
        if body[i] == "}"
          break if depth.zero?
          depth -= 1
        end
        i += 1
      end
      value = body[start_val...i]
      i += 1
    elsif body[i] == '"'
      start_val = i + 1
      i += 1
      while i < body.length && body[i] != '"'
        i += 1
      end
      value = body[start_val...i]
      i += 1
    else
      start_val = i
      i += 1 while i < body.length && body[i] != ","
      value = body[start_val...i]
    end

    fields[name] = clean_text(value)
  end

  fields
end

def clean_text(value)
  text = value.to_s.dup
  text.gsub!(/\\[a-zA-Z]+\s*\{([^{}]*)\}/, "\\1")
  text.gsub!(/\$([^$]*)\$/, "\\1")
  text.gsub!(/[{}]/, "")
  text.gsub!(/\\[_%&]/, "")
  text.gsub!("--", "-")
  text.gsub!(/\s+/, " ")
  text.strip
end

def format_author(name)
  if name.include?(",")
    last, first = name.split(",", 2).map(&:strip)
    initials = first.to_s.split.map { |p| "#{p[0]}." if p[0] }.compact.join(" ")
    "#{last}, #{initials}".strip
  else
    parts = name.split
    return name if parts.empty?

    last = parts.pop
    initials = parts.map { |p| "#{p[0]}." }.join(" ")
    "#{last}, #{initials}".strip
  end
end

def format_authors(author_field)
  authors = author_field.to_s.split(/\s+and\s+/).map(&:strip).reject(&:empty?)
  formatted = authors.map { |a| format_author(a) }
  return "" if formatted.empty?

  if formatted.length > 6
    "#{formatted.first(3).join('; ')}; et al."
  else
    formatted.join("; ")
  end
end

def parse_bib(path)
  text = File.read(path)
  extract_entries(text).map do |entry_text|
    header = entry_text.match(/\A@(\w+)\s*\{\s*([^,]+)\s*,/m)
    next unless header

    key = header[2].strip
    body_start = entry_text.index(",", header.end(2)) + 1
    body_end = entry_text.rindex("}") - 1
    body = entry_text[body_start..body_end]
    Entry.new(key, parse_fields(body))
  end.compact
end

def render(entries)
  grouped = entries.group_by { |e| e.fields["year"].to_i }

  out = []
  out << "---"
  out << "layout: page"
  out << "title: Publications"
  out << "permalink: /papers/"
  out << "---"
  out << ""
  out << "<!-- Auto-generated by scripts/generate_publications.rb. Do not edit manually. -->"
  out << ""
  out << "A complete and continuously updated publication list is available on [Google Scholar](#{SCHOLAR_URL})."
  out << ""

  grouped.keys.sort.reverse.each do |year|
    out << "## #{year}"
    out << ""

    grouped[year].sort_by { |e| e.fields["title"].to_s.downcase }.each do |entry|
      f = entry.fields
      authors = format_authors(f["author"])
      authors = authors.sub(/\.+\z/, "")
      title = f["title"].to_s
      venue = f["journal"].to_s.empty? ? f["publisher"].to_s : f["journal"].to_s
      venue = "Unspecified venue" if venue.empty?
      volume = f["volume"].to_s
      pages = f["pages"].to_s
      doi = f["doi"].to_s
      anchor = entry.key.downcase.gsub(/[^a-z0-9_-]/, "-")

      line = "- <a id=\"#{anchor}\"></a>"
      line += "#{authors}. " unless authors.empty?
      line += "#{title}. *#{venue}*"
      line += " **#{volume}**" unless volume.empty?
      line += " (#{year})"
      line += ", #{pages}" unless pages.empty?
      line += "."
      line += " [doi:#{doi}](https://doi.org/#{doi})" unless doi.empty?
      out << line
    end
    out << ""
  end

  out.join("\n")
end

entries = parse_bib(SOURCE_BIB)
entries.select! { |e| !e.fields["year"].to_s.empty? }

File.write(TARGET_MD, render(entries))
puts "Generated #{TARGET_MD} from #{SOURCE_BIB} (#{entries.length} entries)."
